---
- name: Check hosts
  hosts: hosts
  gather_facts: no
  vars_files:
    - values.yml
  tasks:
    - name: Check ping to hosts (ping)
      ansible.builtin.ping:

    - name: Verificar si el paquete "ansible" está instalado
      package:
        name: ansible
        state: present
      register: ansible_installed
      ignore_errors: yes

    - name: Mostrar mensaje si "ansible" está instalado
      debug:
        msg: "El paquete 'ansible' está instalado en {{ inventory_hostname }}"
      when: ansible_installed is success

    - name: Mostrar mensaje si "ansible" NO está instalado
      debug:
        msg: "El paquete 'ansible' NO está instalado en {{ inventory_hostname }}"
      when: ansible_installed is failed

    - name: Verificar si el paquete "virtualbox" está instalado
      package:
        name: virtualbox
        state: present
      register: vbox_installed
      ignore_errors: yes

    - name: Mostrar mensaje si "virtualbox" está instalado
      debug:
        msg: "El paquete 'virtualbox' está instalado en {{ inventory_hostname }}"
      when: vbox_installed is success

    - name: Mostrar mensaje si "virtualbox" NO está instalado
      debug:
        msg: "El paquete 'virtualbox' NO está instalado en {{ inventory_hostname }}"
      when: vbox_installed is failed

