# values.yml
vms:
  - name: worker1
    memory: 3072
    vcpus: 3
  - name: worker2
    memory: 3072
    vcpus: 3
  - name: worker3
    memory: 3072
    vcpus: 3

master1:
  - name: master1

master2:
  - name: master2

master3:
  - name: master3

worker1:
  - name: worker1

worker2:
  - name: worker2

worker3:
  - name: worker3

prueba:
  - name: prueba
