# values.yml
vms:
  - name: master1
    memory: 3072
    vcpus: 3
  - name: master2
    memory: 3072
    vcpus: 3
  - name: worker3
    memory: 2048
    vcpus: 2

master1:
  - name: master1

master2:
  - name: master2

worker3:
  - name: worker3

hostonlyAdapter: vboxnet0
gateway: 192.168.56.1
