# values.yml
vms:
  - name: master1
    memory: 3072
    vcpus: 3
    ip: 192.168.56.21
  - name: master2
    memory: 3072
    vcpus: 3
    ip: 192.168.56.22
  - name: master3
    memory: 3072
    vcpus: 3
    ip: 192.168.56.23
  - name: worker1
    memory: 2048
    vcpus: 2
    ip: 192.168.56.51
  - name: worker2
    memory: 2048
    vcpus: 2
    ip: 192.168.56.52
  - name: worker3
    memory: 2048
    vcpus: 2
    ip: 192.168.56.53

hostonly_adapter: vboxnet0
