---
- name: Instalar Ubuntu en VM VirtualBox
  hosts: localhost
  gather_facts: no
  vars_files:
    - values.yml
  tasks:
    - name: Crear la VM en VirtualBox
      command: vboxmanage createvm --name {{ item.name }} --ostype Ubuntu_64 --register
      loop: "{{ vms }}"

    - name: Configurar memoria RAM y VRAM de la VM
      command: vboxmanage modifyvm {{ item.name }} --memory {{ item.memory }} --vram 16 --cpus {{ item.vcpus }}
      loop: "{{ vms }}"

    - name: Crear disco duro de 20 GB
      command: vboxmanage createhd --filename ~/VirtualBox\ VMs/{{ item.name }}/{{ item.name }}.vdi --size 20000
      loop: "{{ vms }}"

    - name: Añadir controlador SATA
      command: vboxmanage storagectl {{ item.name }} --name "SATA Controller" --add sata --controller IntelAhci
      loop: "{{ vms }}"

    - name: Vincular disco duro con la controladora SATA
      command: vboxmanage storageattach {{ item.name }} --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium ~/VirtualBox\ VMs/master13/master13.vdi

    - name: Crear controlador IDE y añadir la ISO de Ubuntu
      command: vboxmanage storagectl master13 --name "IDE Controller" --add ide

    - name: Montar la ISO de Ubuntu
      command: vboxmanage storageattach master13 --storagectl "IDE Controller" --port 0 --device 0 --type dvddrive --medium /home/jdherranz/TFG/instalacion_ubuntu/vbox/ubuntu-server-22.04.5.iso

    - name: Montar la ISO de cloud-init
      command: vboxmanage storageattach master13 --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium /home/jdherranz/TFG/instalacion_ubuntu/vbox/seed.iso

    - name: Configurar el arranque de la VM desde la ISO
      command: vboxmanage modifyvm master13 --boot1 dvd --boot2 disk --boot3 none --boot4 none

    - name: Configurar adaptador de red en modo NAT
      command: vboxmanage modifyvm master13 --nic1 nat

    - name: Arrancar la VM para instalar Ubuntu
      command: vboxmanage startvm master13 --type headless
