---
- name: Crear una m치quina virtual en el servidor B
  hosts: servers
  become: true
  vars_files:
    - values.yml
  tasks:
    - name: Crear la m치quina virtual con virt-install
      command: >
        virt-install --name master1 --memory 3072 --vcpus 3 --os-variant ubuntu20.04 --cdrom /var/lib/libvirt/images/ubuntu-desktop-22.04.5.iso --disk size=20 --initrd-inject=/var/lib/libvirt/images/kickstart_ubuntu.ks --extra-args="ks=file:/kickstart_ubuntu.ks"
      args:
        creates: /var/lib/libvirt/images/master1.qcow2

    - name: Arrancar la m치quina virtual para iniciar la instalaci칩n de Ubuntu
      virt:
        name: master1
        state: running
