---
- name: Instalar Ubuntu en VM VirtualBox
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../prueba_values.yml
  tasks:
    - name: Arrancar la VM para instalar Ubuntu
      command: vboxmanage startvm {{ item.name }} --type headless
      loop: "{{ vms }}"

    - name: Esperar a que {{ item.name }} se apague
      shell: VBoxManage showvminfo {{ item.name }} | grep -i 'State' | grep -i 'powered off'
      register: vm_state
      retries: 25   # Número de intentos
      delay: 30     # Segundos entre intentos
      until: vm_state.rc == 0
      ignore_errors: yes
      loop: "{{ vms }}"
