---
- name: Instalar paquetes de kubernetes en los master
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Esperar a que la mv se encienda
      pause:
        seconds: 75

    - name: Instalar dependencias necesarias
      ansible.builtin.apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    - name: Crear el directorio para las claves de apt si no existe
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Descargar la clave pública de Kubernetes
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /tmp/kubernetes-release.key
        mode: '0644'

    - name: Convertir la clave pública a formato gpg
      ansible.builtin.command:
        cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Agregar repo apropiado
      shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list      

    - name: Actualizar la caché de APT
      ansible.builtin.apt:
        update_cache: yes

    - name: Instalar Kubernetes (kubeadm, kubelet, kubectl)
      ansible.builtin.apt:
        name: 
          - kubeadm
          - kubelet
          - kubectl
        state: present

