---
- name: Instalar paquetes en los master
  hosts: prueba
  gather_facts: no
  become: yes
  tasks:
    - name: Añadir el apt-key de  kubernetes
      command: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

    - name: Add el repo de kubernetes
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
