---
- name: Configurar clúster de Kubernetes
  hosts: master
  become: true
  tasks:
  - name: Generar un token para unir nodos al clúster
    ansible.builtin.command: kubeadm token create --print-join-command
    register: join_command
    when: inventory_hostname == 'master1'

  - name: Depurar salida del comando
    ansible.builtin.debug:
      msg: "Join command: {{ join_command.stdout }}"
    when: inventory_hostname == 'master1'

  - name: Extraer el TOKEN del comando generado
    ansible.builtin.set_fact:
      kubeadm_token: "{{ join_command.stdout.split('--token')[1].split()[0] | trim }}"
    when: inventory_hostname == 'master1'

  - name: Extraer el HASH del comando generado
    ansible.builtin.set_fact:
      discovery_hash: "{{ join_command.stdout.split('--discovery-token-ca-cert-hash')[1].split()[0] | trim }}"
    when: inventory_hostname == 'master1'

  - name: Registrar el TOKEN y el HASH como variables globales
    ansible.builtin.set_fact:
      kubeadm_token_global: "{{ hostvars['master1'].kubeadm_token }}"
      discovery_hash_global: "{{ hostvars['master1'].discovery_hash }}"
    delegate_to: localhost
    run_once: true

  - name: Depurar valores extraídos
    ansible.builtin.debug:
      msg:
        - "Token: {{ kubeadm_token_global }}"
        - "Hash: {{ discovery_hash_global }}"
    delegate_to: localhost
    run_once: true

