- name: 1 Creacion de máquinas virtuales
  ansible.builtin.import_playbook: 1-creacion_vm_vbox.yaml

- name: 2 Instalación del SO
  ansible.builtin.import_playbook: 2-instalación_SO_vbox.yaml

- name: 3 Configuracion red e inventario
  ansible.builtin.import_playbook: 3-configuracion_red_e_inventario.yaml

- name: Levantar MVs
  ansible.builtin.import_playbook: Levantar_todos_MVS.yaml

- name: 4 Instalación paquetes kubernetes
  ansible.builtin.import_playbook: 4-Instalación_paquetes_kubernetes.yaml

- name: 5 Configurar SO
  ansible.builtin.import_playbook: 5-configuración_SO.yaml

- name: 6 Desactivar swap
  ansible.builtin.import_playbook: 6-Desactivar_swap_sysctl.yaml

- name: 7 Instalar containerd
  ansible.builtin.import_playbook: 7-Instalar-containerd.yaml

- name: 8 Aumentar tamaño lvm
  ansible.builtin.import_playbook: 8-Aumentar_tamaño_lv.yaml

- name: 9 Instalar kubernetes
  ansible.builtin.import_playbook: 9-Instalar-kubernetes.yaml

- name: 10 Instalar Calico y dashboard
  ansible.builtin.import_playbook: 10-Calico-dashboard.yaml

- name: 11 Distribuir kube config
  ansible.builtin.import_playbook: 11-Distribuir_kube_config.yaml

- name: 12 Creación app de nginx
  ansible.builtin.import_playbook: 12-Creación_app.yaml

