---
- name: Levantar todas las MVs
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../values.yml
  tasks:
    - name: Levantar cada máquina virtual
      ansible.builtin.command: vboxmanage startvm "{{ item.name }}" --type headless
      ignore_errors: yes
      register: result
      loop: "{{ vms }}"

    - name: Refrescar inventario dinámicamente
      meta: refresh_inventory
