---
- name: Configurar clúster de Kubernetes
  hosts: master
  become: true
  tasks:
  - name: Inicializar el clúster de Kubernetes en el primer maestro
    ansible.builtin.command: |
      kubeadm init --control-plane-endpoint "{{ hostvars['master1']['ansible_host'] }}" --pod-network-cidr=192.168.0.0/16
    when: inventory_hostname == 'master1'

  - name: Copiar el archivo kubeconfig para el usuario actual
    ansible.builtin.shell: |
      mkdir -p $HOME/.kube 
      cp -i /etc/kubernetes/admin.conf $HOME/.kube/config 
      chown $(id -u):$(id -g) $HOME/.kube/config
    when: inventory_hostname == 'master1'

  - name: Generar un token para unir nodos al clúster
    ansible.builtin.command: kubeadm token create --print-join-command
    register: join_command
    when: inventory_hostname == 'master1'

  - name: Extraer el TOKEN del comando generado
    ansible.builtin.set_fact:
      kubeadm_token: "{{ join_command.stdout.split('--token')[1].split()[0] | trim }}"
    when: inventory_hostname == 'master1'

  - name: Extraer el HASH del comando generado
    ansible.builtin.set_fact:
      discovery_hash: "{{ join_command.stdout.split('--discovery-token-ca-cert-hash')[1].split()[0] | trim }}"
    when: inventory_hostname == 'master1'

  - name: Registrar el TOKEN y el HASH como variables globales
    ansible.builtin.set_fact:
      kubeadm_token_global: "{{ hostvars['master1'].kubeadm_token }}"
      discovery_hash_global: "{{ hostvars['master1'].discovery_hash }}"
    delegate_to: localhost
    run_once: true

  - name: Unirse al clúster como maestro
    ansible.builtin.command: |
      kubeadm join {{ hostvars['master1']['ansible_host'] }}:6443 --token {{ kubeadm_token_global }} \
      --discovery-token-ca-cert-hash sha256:{{ discovery_hash_global }} --control-plane
    when: inventory_hostname != 'master1'
